### ISSUE TITLE
Taxonomic mismatches when using `lsid` for some atlases

### ISSUE THREAD

**Issue by mjwestgate** [AtlasOfLivingAustralia/galah-R#165]
**Affected atlases:**

- Estonia (https://elurikkus.ee)
- France (https://inpn.mnhn.fr)
- Sweden (https://biodiversitydata.se)

If I run:
```
galah_config(atlas = "Estonia")
galah_call() |>
      galah_identify("Mammalia") |>
      atlas_counts()
```
I get a count of 44 records returned, whereas:
```
galah_call() |>
      galah_filter(class == "Mammalia") |>
      atlas_counts()
```
Returns a count of 117,448 records, which seems more likely. This appears to be an issue with `elurikkus.ee` not recognising  `(lsid:11618)` as a query via the `fq` parameter in the `https://elurikkus.ee/biocache-service/occurrences/search` API.

**Comment by vjrj** [comment]
cc @shahmanash @sylmorin-gbif

**Comment by vjrj** [comment]
Maybe, better to use openobs https://living-atlases.gbif.org/participants/openobs/ , right @sylmorin-gbif ?

**Comment by sylmorin-gbif** [comment]
Hi,
I agree with @vjrj , please use OpenObs (https://living-atlases.gbif.org/participants/openobs/) for France instead.

**Comment by mjwestgate** [comment]
It appears that updates the taxonomy sometimes break links between the taxonomic and biocache services, regardless of which living atlas is involved. Closing this, but have added tests to pick it up when it happens
