### ISSUE TITLE
Support common filtering functions within `galah_filter()`

### ISSUE THREAD

**Issue by daxkellie** [AtlasOfLivingAustralia/galah-R#196]
With the shift to using Advanced R syntax for parsing logical statements in `galah_filter()` (#169), `galah_filter()` is now better structured to identify when users have supplied other functions like `is.na()` to `galah_filter()`. As a result, adding support for common filtering functions will help users use familiar syntax to edit queries.

The proposed change will allow users to do things like:
```{r}
galah_call() |>
  identify("reptilia") |>
  filter(!is.na(species)) |>
  collect("counts")
```

**Comment by mjwestgate** [comment]
Supported as of version 2.0
