### ISSUE TITLE
atlas_occurrences is not downloading data

### ISSUE THREAD

**Issue by fernandabiologia** [AtlasOfLivingAustralia/galah-R#205]
Hi,

Thanks for creating  the galah package. It has been super helpful. 

I was using the package just fine yesterday, but today when I try to use the function atlas_occurrences(). I either get the message below which keeps stuck on it and nothing happens: 

**This query will return 625 records

Checking queue
Current queue size: 2 inqueue ............................**

Or I get this error message:

This query will return 556 records

**Checking queue
Current queue size: Error in if (status$queueSize < queue_size & status$queueSize > 0) { : 
  argument is of length zero**

I wrote down this issue as a bug but could this be a server issue since everything was working yesterday?

Thanks,

Fernanda.

**Comment by daxkellie** [comment]
Thanks for reaching out about this problem. We are investigating this on the server and I think there might be a slight delay on downloads at the moment. I will let you know when this is resolved!

**Comment by daxkellie** [comment]
Hi @fernandabiologia,
Just following up that downloads appear to be working again. Sorry for the inconvenience but thanks for letting us know about the issue so we could look into it 😃

**Comment by fernandabiologia** [comment]
Hi @daxkellie,

Yes it it. I was just able to download again. Thanks for looking into it :)

**Comment by fernandabiologia** [comment]
Hi @daxkellie,

Yes it is. I just tried it again and it works. Thanks for looking into it :)
