### ISSUE TITLE
Add further options to `galah_select()`

### ISSUE THREAD

**Issue by mjwestgate** [AtlasOfLivingAustralia/galah-R#218]
At present there are two use cases for `galah_select()` that are not supported:
- option to deliver _all_ fields (`group = "all"`?)
- option to deliver the _default fields for that atlas_ (`group = "default"`?) i.e. the same as from the biocache

**Comment by mjwestgate** [comment]
- decision not to add `group = "all"`
- add `group = "taxonomy"` to get higher taxonomic columns

**Comment by daxkellie** [comment]
Implemented in version 2.0.2
