### ISSUE TITLE
Consider setting `ala_media()` to provide only open licensed images by default

### ISSUE THREAD

**Issue by mjwestgate** [AtlasOfLivingAustralia/galah-R#24]
This would work in a similar way to `select_columns(group = 'basic')` as it relates to `ala_occurrences()`, but in this case would require some sort of `group` argument in `select_filters()` that would be activated when passed to `ala_media()`. 

An obvious solution would be to set a data quality profile (e.g. called 'open_images') on the ALA side that includes only open licences, and call this using `select_filters(profile = 'open_images')`. There was talk about doing this for occurrence records already, so this may use the same profile as that, or a slight variation on it.

**Comment by matildastevenson** [comment]
Is it possible to set a data quality profile which uses the image licence information? I thought image licence is a property of the image, rather than the occurrence record.

**Comment by matildastevenson** [comment]
@mjwestgate and I had a chat about this and decided to add a function to help users filter by class of licence, but not add a filter by default. 
The function would be something like `licence(type = "unrestricted")`, where type is one of `c("unrestricted", "non-commercial"... )`. A user would specify the licence category in `select_filters` e.g. 
```
ala_media(filters = select_filters(license = licence(type = "non-commercial")
```
`licence` function should have `license` alias to allow either spelling

**Comment by matildastevenson** [comment]
Thinking about this some more, the `licence` function would need to take a number of arguments e.g. commercial_use, derivative_use, attribution_required to work out which licences are applicable. But then it might be easier for the user to just look up the licences

**Comment by matildastevenson** [comment]
As of the infrastructure upgrade, there is now a `multimediaLicense` field attached to occurrence records. This is populated by the data provider, and not derived from the images. This would allow licence filtering without needing to first download the image metadata. However, the field is not mapped to a controlled vocabulary

**Comment by mjwestgate** [comment]
media functions have been modularised as of version 2.0, enabling users to filter at various points in the workflow. Could revisit wrapper functions at a later time if there is a pressing need
