### ISSUE TITLE
`?search_taxa()` doesn't return correct help documentation

### ISSUE THREAD

**Issue by daxkellie** [AtlasOfLivingAustralia/galah-R#241]
`search_taxa()` has more bespoke functionality to other `search_all()` functions because searching taxonomy is a little more complex. It _should_ have its own documentation to help users that we wrote specifically for it (and `search_identifiers()`.

When running `?search_taxa()`, this documentation no longer appears, and instead the `search_all()` documentation is shown. Odds are `search_taxa()` has accidentally been filed under the `search_all()` documentation when it shouldn't be.

**Comment by daxkellie** [comment]
This was most likely the last version of the documentation: https://github.com/AtlasOfLivingAustralia/galah-R/blob/030357197bda142cb60beb749c73fd2fb215addd/R/search_taxa.R

**Comment by mjwestgate** [comment]
Closed as completed
